site_name: ConFIG
site_description: Official Implementation for Conflict-Free Inverse Gradients Method.
site_author: Qiang Liu
site_url: https://tum-pbs.github.io/ConFIG

repo_url: https://github.com/tum-pbs/ConFIG
repo_name: tum-pbs/ConFIG
edit_uri: ""  # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate

theme:
    name: material
    features:
        #- navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
    palette:
        - scheme: default
          primary: brown
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: brown
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
    logo: assets/config_white.svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/qiauil


strict: true  # Don't allow warnings during the build process

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - mknotebooks  # Jupyter notebooks
    - mkdocstrings:
        handlers:
            python:
                options:
                    inherited_members: true  # Allow looking up inherited methods
                    show_root_heading: true  # actually display anything at all...
                    show_root_full_path: true  # display full path
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    separate_signature: true
                    show_source: true  # don't include source code
                    members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                    heading_level: 4
                    show_symbol_type_heading: true
                    docstring_style: google

nav:
    - 'General Instructions': 'index.md'
    - 'Examples': 
        - 'Toy example of Muti-task Learning': 'examples/mtl_toy.ipynb'
        - "Solve Burgers' Equation with PINN": 'examples/pinn_burgers.ipynb'
    - 'API Reference':
        - "Gradient operator": 'api/grad_operator.md'
        - "Momentum operator": 'api/momentum_operator.md'
        - "Weight Model": 'api/weight_model.md'
        - "Length Model": 'api/length_model.md'
        - "Utils": 'api/utils.md'
